import MainWrapper from "@/layout/layoutWrappers/MainWrapper";
import "@/styles/globals.css";
import "@/styles/index.css";
import type { AppProps } from "next/app";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>RS Freaks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icons/tab-logo.svg" />
      </Head>
      <Provider store={store}>
        <MainWrapper>
          <Component {...pageProps} />
        </MainWrapper>
      </Provider>
    </>
  );
}
